import Navbar from "../features/Navbar";
import "../styles/globals.css";
import Head from "next/head";
import { motion, AnimatePresence } from "framer-motion";

function MyApp({ Component, pageProps, router }) {
  return (
    <>
      <Head>
        <title>Youssef portifolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <AnimatePresence exitBeforeEnter>
        <motion.div key={router.route} exit={{ y: -1000 }}>
          <Component {...pageProps} />
        </motion.div>
      </AnimatePresence>
    </>
  );
}

export default MyApp;
