import Head from "next/head";
import homeStyles from "../styles/Home.module.css";
import Landing from "../components/Landing";
export default function Home() {
  return (
    <>
      <Head>
        <title>Youssef portifolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ overflow: "hidden" }}>
        <Landing />
      </div>
    </>
  );
}
