import Head from "next/head";
import Landing from "../components/Landing";
import Loading from "../components/Loading";
export default function Home() {
  return (
    <>
      <div className="overflow-hidden">
        <Head>
          <title>Youssef portifolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Landing />
      </div>
      <Loading />
    </>
  );
}
